### ISSUE TITLE
Autocomplete triggering on reserved words and comments.

### ISSUE THREAD

**Issue by mhoff12358** [ZoeyR/rls-vs2017#25]
Language syntax words like "for" or "as" will autocomplete automatically to "format!" or "assert!" making it impossible to type those statements without explicitly using the escape key whenever I type one of those words.
Similarly, autocomplete automatically happens whenever I type a comment totally messing up the actual comment contents.

This is on visual studio 2019 version 16.1.1

**Comment by alexchandel** [comment]
@ZoeyR is this an issue with RLS, or this extension?  Or is Visual Studio itself unable to ban reserved words from its autocomplete / snippets?

**Comment by ZoeyR** [comment]
This would be an issue with the RLS. As a rule Visual Studio cannot (and should not) know about language-specific keywords. It's up to the language server to not return completions in these scenarios. This could be an issue I've seen where RLS doesn't like CRLF line endings and returns completions when it shouldn't.
