### ISSUE TITLE
Extension fails to start

### ISSUE THREAD

**Issue by technic** [ZoeyR/rls-vs2017#27]
There was an error activating the remote language server, Rust Language Extension.

## From the log
`
895 ERROR System.MissingMethodException: Method not found: 'Void Microsoft.VisualStudio.LanguageServer.Protocol.TextDocumentClientCapabilities.set_CodeAction(Microsoft.VisualStudio.LanguageServer.Protocol.DynamicRegistrationSetting)'. at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageServiceBroker.RemoteLanguageClientInstance.<InitializeAsync>d__49.MoveNext() at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine) at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageServiceBroker.RemoteLanguageClientInstance.InitializeAsync(String workspaceLocation, CancellationToken token) at Microsoft.VisualStudio.LanguageServer.Client.RemoteLanguageServiceBroker.RemoteLanguageClientInstance.<ActivateLanguageClientAsync>d__47.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) 
`

## Version info

Microsoft Visual Studio Community 2017 
Version 15.9.16
VisualStudio.15.Release/15.9.16+28307.858
Microsoft .NET Framework
Version 4.7.02558

**Comment by ZoeyR** [comment]
That would be a bug in visual studio, not the extension. Use the developer feedback tool to report it.
