### ISSUE TITLE
VS 2022 support

### ISSUE THREAD

**Issue by inequation** [ZoeyR/rls-vs2017#29]
May I please request updating this extension to VS 2022? :) I've found it very useful in VS 2019, and I have no experience with extension development to do it myself.

**Comment by MurraySobol** [comment]
I assume this is the problem: Skipping product Microsoft.VisualStudio.Product.BuildTools (f998b78e) since it does not support extensions??

**Comment by inequation** [comment]
I've managed to get it to work in VS2022 in my fork eventually:
https://github.com/inequation/rls-vs2022/releases/tag/vs2022
But I'd actually advise against using it. You're better off using https://github.com/cchharris/VS-RustAnalyzer instead.
